### PR TITLE
Refactoring onit

### PR DESCRIPTION
**Pull request by adibrastegarnia**
The first PR to address issue #53

### CODE REVIEW

**Comment by kuujo** [comment]
I think `controller` might make sense. It can contain the interfaces for controllers, even though there's currently only one of those.

**Comment by adibrastegarnia** [comment]
> I think `controller` might make sense. It can contain the interfaces for controllers, even though there's currently only one of those.

Will take care of it.

**Comment by kuujo** [comment]
Actually, maybe it should be:
* `onit`
   * `cli`
   * `console`
   * `controller`
      * `interfaces.go`
      * `k8s`
         * `cluster.go`
         * ...
      * `local`
         * `cluster.go`
         * ...

**Comment by adibrastegarnia** [comment]
> Actually, maybe it should be:
> 
>     * `onit`
>       
>       * `onit.go`
>       * `cli`
>       * `console`
>       * `controller`
>         
>         * `interfaces.go`
>         * `k8s`
>           
>           * `cluster.go`
>           * ...
>         * `local`
>           
>           * `cluster.go`
>           * ...
> 
> 
> Does that seem logical?

I think so. The implementations refer to the same file names which makes it beautiful.

**Comment by adibrastegarnia** [comment]
Something is still not right. The interface and implementation are disconnected from each other. I am working on that.

**Comment by adibrastegarnia** [comment]
To use the interface we need to have something like this:

`var k8sCluster interfaces.ClusterController`
`k8sCluster = cluster`   //cluster here is the return value of 
`cluster, status := controller.NewCluster(clusterID, config)`

**Comment by kuujo** [comment]
Yep that seems right...

A couple things. First, I think `onit/k8s/controller` should be in the `onit` package. It's a controller for _all_ clusters, and should be able to support deployment of either local or k8s clusters. So this should not be in the k8s package.

And related, the controller is also responsible for _deleting_ clusters, so I think the `ClusterController` interface needs to have a `Teardown` method also.

It feels a little weird to have `onit/controller.go` and then a package `onit/controller` has interfaces for `ClusterController`. I think we should move `onit/k8s/controller.go` to `onit/controller.go` and rename `onit/controller` to `onit/cluster` to contain the base interfaces/utilities for cluster controllers and avoid cyclic dependencies.

**Comment by adibrastegarnia** [comment]
> Yep that seems right...
> 
> A couple things. First, I think `onit/k8s/controller` should be in the `onit` package. It's a controller for _all_ clusters, and should be able to support deployment of either local or k8s clusters. So this should not be in the k8s package.
> 
> And related, the controller is also responsible for _deleting_ clusters, so I think the `ClusterController` interface needs to have a `Teardown` method also.
> 
> It feels a little weird to have `onit/controller.go` and then a package `onit/controller` has interfaces for `ClusterController`. I think we should move `onit/k8s/controller.go` to `onit/controller.go` and rename `onit/controller` to `onit/cluster` to contain the base interfaces/utilities for cluster controllers and avoid cyclic dependencies.

Done.

**Comment by adibrastegarnia** [comment]
@kuujo 
Perhaps we should postpone this until we get some of the basics that we need into the repo and then I will open a new one.

**Comment by adibrastegarnia** [comment]
Will open a new one when we have other PRs merged.

**Pull request closed without merging**
