### PR TITLE
Refactoring onit to implement local cluster

### PR DESCRIPTION
**Pull request by adibrastegarnia**
To address issue #50

### CODE REVIEW

**Comment by kuujo** [comment]
Why are we making the fields of `ClusterController` public?

**Comment by adibrastegarnia** [comment]
> Why are we making the fields of `ClusterController` public?
@kuujo 
Because it is not in onit package anymore and we need to access them in other packages like controller when we create an instance of that if it is supposed to have controller.go in onit package.

**Comment by adibrastegarnia** [comment]
@kuujo 
there is also another thing that I am not sure about. Suppose we want to implement TearDown function for k8s Cluster What we do now in delete function is to call controller.DeleteCluster(clusterID). If we want to call that function and other related lines that are in delete cluster function, we will end up  a cycle in imports. The question is how should we go for TearDown function?

**Comment by adibrastegarnia** [comment]
> @kuujo
> there is also another thing that I am not sure about. Suppose we want to implement TearDown function for k8s Cluster. What we do now in delete function is to call controller.DeleteCluster(clusterID). If we want to call that function and other related lines that are in delete cluster function, we will end up a cycle in imports. The question is how should we go for TearDown function?

Perhaps what we can do is to write the delete function part of cluster.go since it has access to kubclient that we need to delete a cluster.

**Comment by kuujo** [comment]
But the fields in `k8s.ClusterController` are specific to k8s, so they should still only be accessed by the `onit/k8s` package, right? The `local.ClusterController` will have its own fields that only need to be visible in its package.

If the reason those fields are publicly visible is because the main `Controller` needs to construct the `k8s.ClusterController`, we should add a `k8s.NewClusterController` function to set them.

**Comment by adibrastegarnia** [comment]
> But the fields in `k8s.ClusterController` are specific to k8s, so they should still only be accessed by the `onit/k8s` package, right? The `local.ClusterController` will have its own fields that only need to be visible in its package.
> 
> If the reason those fields are publicly visible is because the main `Controller` needs to construct the `k8s.ClusterController`, we should add a `k8s.NewClusterController` function to set them.

Yes. You are right. I will take care of it.

**Pull request merged**
