### PR TITLE
refactoring the onit cluster

### PR DESCRIPTION
**Pull request by adibrastegarnia**
The first PR to address issue #50

### CODE REVIEW

**Comment by kuujo** [comment]
I don't think we want to rename `onit` to `k8s`. I think `k8s` should be a package under `onit`, and `onit` should contain both `k8s` and `local`. We definitely want to keep all the code that controls tests in one package (onit) and all the code that runs tests in another (runner).

**Comment by kuujo** [comment]
Then the `onit` package can contain the interfaces that are implemented in `onit/k8s` and `onit/local`. Although we may have to use a third package to avoid circular dependencies.

**Comment by adibrastegarnia** [comment]
> Then the `onit` package can contain the interfaces that are implemented in `onit/k8s` and `onit/local`. Although we may have to use a third package to avoid circular dependencies.
@kuujo 
OK. I thought you want to have two top packages. I revert the changes

**Comment by kuujo** [comment]
BTW I would pull out the interfaces in this PR as well. Then we can merge it so we don't mess too much with @ray-milkey and then finish the local implementation.

**Comment by adibrastegarnia** [comment]
closed and will open a new one.

**Pull request closed without merging**
