### PR TITLE
Update simulator OpenConfig model

### PR DESCRIPTION
**Pull request by adibrastegarnia**
This PR updates the simulator config model to include some of the new state variables such as current-date-time to the model.

### CODE REVIEW

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia I'm ok with loading initial configuration to the simulator but I think state should not be part of this initial configuration. Date and time can be fetched easily from the system and and that simplifies life for testing suites because the avoid the need of hardcoding any value. 
Also please extract the configuration as a json file and read it in. modifying code for a json change is bad practice. 
Also please do check that any modifications you have here are also ported to 
https://github.com/onosproject/onos-helm-charts/blob/master/device-simulator/files/configs/ofsw_config.json

I'm debating if we have to have a unique place for this, thoughts ?

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 
Yes we discussed it with @kuujo and at the moment we cannot read the config files from config files since we add simulators inside k8s when compared with the previous architecutre that we were adding resources outside of k8s.
>_Jordan's response: Yeah that created problems when we started deploying simulators from inside k8s. When we were creating k8s resources from the client, the client would just be reading its local file system. But when we compile the binary those files are lost, so we'd need to ensure they're added to any image onit is used in, which becomes a PITA since those are then test images. So that's why I switched to static values

I have an idea just for the simulator but not tested yet to see if it is feasible so I should discuss it with Jordan first, I will let you know. 

Regarding the initial config: Initial config acts also as a template for the simulator to have an idea about the fields that exist in the configuration. The simulator loads the initial config in a json tree and updates the values during runtime whenever there is a set request and retrieves the value whenever there is a get or subscribe request. That is also true for state variables that should be updated during runtime. For example, when we start the gnmi server, it loads the initial config, it starts updating current-date-time value using the system time (from the beginning) and it keeps updating it during runtime. That means state variables in the config file just specify the field and its acceptable format the correct value is initialized whenever we start the server (at the moment just for current-date-time field).

I don't think having a unique place is going to make things easier. At least for the simulator, anyone should be able to use the simulator independent of other repos. If we want to think about a place to put simulator config file, it should be the simulator repo but we should think about the complexities that potentially can be introduced in onos-test or anywhere we want to use that config file.

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia I see your point about not being able to load the config externally. Let's leave it as is for now but please do update the one used in https://github.com/onosproject/onos-helm-charts/blob/master/device-simulator/files/configs/ofsw_config.json to match 1:1 the one used here or we could encounter some issue when deploying the simulator through HELM. 

regarding the "template" I see what you mean, maybe for the "state" can it be left to just the path and empty value ? telling the simulator you should have something at this path and then letting it populate. 

Please put a comment in the class stating the purpose of that json and a //TODO to extract it.

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 
Thanks for your comments. I will take care of your comments in the next few days or so.

**Comment by Andrea-Campanella** [comment]
@adibrastegarnia thanks! Ping me for review.

**Comment by adibrastegarnia** [comment]
@Andrea-Campanella 
We cannot let the fields to be empty because simulator uses ygot to validate the initial config and it should be correct based on the openConfig model.

**Pull request merged**
